<?xml version="1.0"?>
<package format="3">
  <name>arcz_bringup</name>
  <version>0.0.1</version>
  <description>Top-level launch/config that brings up the whole arcz stack</description>
  <maintainer email="radek.domin@gmail.com">Radek</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>arcz_connection</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
